name: GitHub Models Workflow Precheck

on:
  workflow_call:

jobs:
  precheck:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ✅ use for API auth

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build prompt from calling workflow
        run: |
          echo "You're a GitHub Actions expert. Analyze this workflow and tell me:
- Will it likely fail?
- Why?
- How to fix it?
---" > prompt.txt

          WORKFLOW_NAME=$(basename "${{ github.workflow_ref }}")
          cat ".github/workflows/$WORKFLOW_NAME" >> prompt.txt || echo "⚠ Missing workflow"

      - name: Call GitHub Models API
        run: |
          PROMPT=$(<prompt.txt)

          curl -s "https://models.github.ai/inference/chat/completions" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d @- <<EOF > model_response.json
{
  "model": "openai/gpt-4o",
  "messages": [
    {
      "role": "user",
      "content": "$PROMPT"
    }
  ]
}
EOF

          echo "✅ Raw Response:"
          cat model_response.json | jq '.choices[0].message.content' > model_response.txt

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: model-analysis
          path: model_response.txt

      - name: Exit if Failure Predicted
        run: |
          cat model_response.txt
          if grep -iE 'fail|error|likely.*fail|fix|issue' model_response.txt; then
            echo "❌ Workflow predicted to fail"
            exit 1
          else
            echo "✅ Safe to run"
          fi
